name: Feature
description: Solicitar una nueva capacidad o mejora funcional
title: "[FEATURE] "
body:
  - type: textarea
    id: problem
    attributes:
      label: Necesidad / problema
      description: Explicar la necesidad o problema que se busca resolver.
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Solución propuesta
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Criterios de aceptación
      placeholder: |
        - [ ] Criterio 1
        - [ ] Criterio 2
    validations:
      required: true
